[package]
name = "wasm-component"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { path = "/home/danielbevenius/work/wasm/wit-bindgen/crates/guest-rust", version = "0.6.0" }

[lib]
crate-type = ["cdylib"]
