// Generated by `wit-bindgen` 0.6.0. DO NOT EDIT!
package wit_component;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

import org.teavm.interop.Memory;
import org.teavm.interop.Address;
import org.teavm.interop.Import;
import org.teavm.interop.Export;
import org.teavm.interop.CustomSection;

public final class ComponentWorld {
    private ComponentWorld() {}
    
    @Export(name = "something")
    private static int wasmExportSomething(int p0, int p1) {
        
        byte[] bytes = new byte[p1];
        Memory.getBytes(Address.fromInt(p0), bytes, 0, p1);
        
        String result = ComponentWorldImpl.something(new String(bytes, StandardCharsets.UTF_8));
        
        byte[] bytes0 = (result).getBytes(StandardCharsets.UTF_8);
        
        Address address = Memory.malloc(bytes0.length, 1);
        Memory.putBytes(address, bytes0, 0, bytes0.length);
        Address.fromInt((ComponentWorld.RETURN_AREA) + 4).putInt(bytes0.length);
        Address.fromInt((ComponentWorld.RETURN_AREA) + 0).putInt(address.toInt());
        return ComponentWorld.RETURN_AREA;
        
    }
    
    @Export(name = "cabi_post_something")
    private static void wasmExportSomethingPostReturn(int p0) {
        Memory.free(Address.fromInt(Address.fromInt((p0) + 0).getInt()), Address.fromInt((p0) + 4).getInt(), 1);
        
    }
    
    @CustomSection(name = "component-type:Component")
    private static final String __WIT_BINDGEN_COMPONENT_TYPE = "020009636f6d706f6e656e7409636f6d706f6e656e7409636f6d706f6e656e740061736d0c000100074201410201410201400101737300730409736f6d657468696e670001000409636f6d706f6e656e7418706b673a2f636f6d706f6e656e742f636f6d706f6e656e740400004a0970726f647563657273010c70726f6365737365642d6279020d7769742d636f6d706f6e656e7405302e382e32167769742d62696e6467656e2d746561766d2d6a61766105302e362e300b1d0109636f6d706f6e656e740e706b673a2f636f6d706f6e656e74030000";
    
    public static final int RETURN_AREA = Memory.malloc(8, 4).toInt();
}
