[package]
name = "wasi-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "18.0.1"

[[bin]]
name = "basic"
path = "src/main.rs"

[[bin]]
name = "host"
path = "src/host-func.rs"
