#![allow(dead_code)]
#![allow(unused_braces)]
// Uncommenting to have the wit-bindgen bindings generated by the macro.
//wit_bindgen::generate!("component");

mod component;
use component::*;

struct Something;

impl component::Component for Something {
    fn something(s: String) -> String {
        format!("something was passed: {s}")
    }
}

export_component!(Something);
