[package]
name = "wasm-encoder-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-encoder = "0.201.0"
wasmparser = "0.201.0"
